"""Cambio pieza unica a figuras ensambladas

Revision ID: 34fe67754b19
Revises: ad77d3070ac9
Create Date: 2026-03-13 10:27:06.570146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34fe67754b19'
down_revision: Union[str, Sequence[str], None] = 'ad77d3070ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos_cotizacion', sa.Column('figuras_ensambladas_total', sa.Integer(), nullable=True))
    op.drop_column('proyectos_cotizacion', 'es_pieza_unica')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos_cotizacion', sa.Column('es_pieza_unica', sa.BOOLEAN(), nullable=True))
    op.drop_column('proyectos_cotizacion', 'figuras_ensambladas_total')
    # ### end Alembic commands ###
