"""Add audit formulas to bandeja

Revision ID: 8999832aa9bd
Revises: 34fe67754b19
Create Date: 2026-03-13 10:36:37.602382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8999832aa9bd'
down_revision: Union[str, Sequence[str], None] = '34fe67754b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bandejas_detalle', sa.Column('formula_tiempo', sa.String(), nullable=True))
    op.add_column('bandejas_detalle', sa.Column('formula_energia', sa.String(), nullable=True))
    op.add_column('bandejas_detalle', sa.Column('formula_desgaste', sa.String(), nullable=True))
    op.add_column('bandejas_detalle', sa.Column('formula_material', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bandejas_detalle', 'formula_material')
    op.drop_column('bandejas_detalle', 'formula_desgaste')
    op.drop_column('bandejas_detalle', 'formula_energia')
    op.drop_column('bandejas_detalle', 'formula_tiempo')
    # ### end Alembic commands ###
