"""Initial migration

Revision ID: ad77d3070ac9
Revises: 
Create Date: 2026-03-13 09:46:33.687508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad77d3070ac9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos_cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('es_nuevo', sa.Boolean(), nullable=True),
    sa.Column('operacion_24h', sa.Boolean(), nullable=True),
    sa.Column('es_cama_llena', sa.Boolean(), nullable=True),
    sa.Column('es_pieza_unica', sa.Boolean(), nullable=True),
    sa.Column('peso_total_g', sa.Float(), nullable=True),
    sa.Column('tiempo_real_h', sa.Float(), nullable=True),
    sa.Column('tiempo_efectivo_h', sa.Float(), nullable=True),
    sa.Column('piezas_total', sa.Integer(), nullable=True),
    sa.Column('num_bandejas', sa.Integer(), nullable=True),
    sa.Column('costo_material', sa.Float(), nullable=True),
    sa.Column('costo_energia', sa.Float(), nullable=True),
    sa.Column('costo_desgaste', sa.Float(), nullable=True),
    sa.Column('costo_mano_obra', sa.Float(), nullable=True),
    sa.Column('costo_base_operativo', sa.Float(), nullable=True),
    sa.Column('factor_riesgo_material', sa.Float(), nullable=True),
    sa.Column('factor_riesgo_modelo', sa.Float(), nullable=True),
    sa.Column('factor_riesgo_total', sa.Float(), nullable=True),
    sa.Column('factor_penalizacion_tiempo', sa.Float(), nullable=True),
    sa.Column('costo_tecnico_final', sa.Float(), nullable=True),
    sa.Column('pvp_comercial_promedio', sa.Float(), nullable=True),
    sa.Column('pvp_productivo', sa.Float(), nullable=True),
    sa.Column('pvp_cama_llena', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyectos_cotizacion_id'), 'proyectos_cotizacion', ['id'], unique=False)
    op.create_index(op.f('ix_proyectos_cotizacion_nombre'), 'proyectos_cotizacion', ['nombre'], unique=False)
    op.create_table('bandejas_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('impresora_key', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('tiempo_horas', sa.Float(), nullable=True),
    sa.Column('peso_gramos', sa.Float(), nullable=True),
    sa.Column('altura_capa', sa.Float(), nullable=True),
    sa.Column('boquilla', sa.Float(), nullable=True),
    sa.Column('piezas', sa.Integer(), nullable=True),
    sa.Column('tiempo_efectivo', sa.Float(), nullable=True),
    sa.Column('costo_energia', sa.Float(), nullable=True),
    sa.Column('costo_desgaste', sa.Float(), nullable=True),
    sa.Column('costo_material', sa.Float(), nullable=True),
    sa.Column('factor_altura', sa.Float(), nullable=True),
    sa.Column('factor_boquilla', sa.Float(), nullable=True),
    sa.Column('es_material_tecnico', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos_cotizacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bandejas_detalle_id'), 'bandejas_detalle', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bandejas_detalle_id'), table_name='bandejas_detalle')
    op.drop_table('bandejas_detalle')
    op.drop_index(op.f('ix_proyectos_cotizacion_nombre'), table_name='proyectos_cotizacion')
    op.drop_index(op.f('ix_proyectos_cotizacion_id'), table_name='proyectos_cotizacion')
    op.drop_table('proyectos_cotizacion')
    # ### end Alembic commands ###
